import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '../components/Header';
import Footer from '../components/Footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'SOI',
  description: 'Generated by create next app ',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} grid min-h-screen grid-rows-[auto_1fr_auto] antialiased`}
      >
        <header className="flex items-center justify-center bg-gray-800 p-4 text-white">
          <Header />
        </header>
        <main className="bg-gray-100 p-4">{children}</main>
        <h1 className="text-black">kjlkjlkj</h1>
        <footer className="bg-gray-800 p-4 text-white">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
